#!/bin/bash

#Run in specific nodes only
#SBATCH --nodelist=hudson

#Hard runtime (HH:MM:SS)
#SBATCH --time=0:10:00

#SBATCH --job-name=cg_async

#Run in the nvidia partition
#SBATCH --partition=nvidia

#Output file
#SBATCH --output=slurm_outputs/cg_async_result-%j.out

#Number of GPUs for the job
#SBATCH --gpus=2
#SBATCH --cpus-per-gpu=1

#Change to directory where 'sbatch' was called
cd $SLURM_SUBMIT_DIR
cd results
mkdir job_$SLURM_JOB_ID
cd job_$SLURM_JOB_ID

#Run my program
srun julia ~/JACC.jl/cg_async_benchmark.jl
